version: "3.3"
services: 
  mongodb:
    build: 
      context: ./mongo
      dockerfile: Dockerfile
    volumes:
      - todoapp_db:/data/mongodb
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    depends_on: 
      - mongodb

  frontend:
    build: ./frontend
    ports: 
      - 80:80
    depends_on: 
      - backend

volumes:
  todoapp_db: {}